In [35]:
#Cargamos librerias 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [36]:
#Carga desde un archivo .csv sin indice y eliminar filas innecesarias
dfh=pd.read_csv("hong_kong_limpio.csv")
dfh.head(5)

Unnamed: 0  host_listings_count  host_total_listings_count  latitude  \
0           0                    1                        1.0  22.28228   
1           1                    1                        1.0  22.27723   
2           2                    1                        1.0  22.27924   
3           3                    3                       19.0  22.30000   
4           4                    2                        2.0  22.28376   

   longitude  accommodates  bathrooms  bedrooms  beds   price  ...  \
0  114.14923           2.0        1.0       1.0   1.0   800.0  ...   
1  114.15083           8.0        2.5       3.0   6.0   645.0  ...   
2  114.16995           4.0        1.0       2.0   3.0   819.0  ...   
3  114.20000           6.0        2.0       3.0   3.0   959.0  ...   
4  114.15313           2.0        2.0       1.0   1.0  1001.0  ...   

         room_type  bathrooms_text  \
0  Entire home/apt          1 bath   
1     Private room       2.5 baths   
2  Entire home/apt          1 bath   
3  Entire home/apt         2 baths   
4  Entire home/apt         2 baths   

                                           amenities  calendar_updated  \
0  ["Extra pillows and blankets", "Heating", "Kit...             nulos   
1  ["Dishes and silverware", "Washer", "Dryer", "...             nulos   
2  ["Washer", "Clothing storage: wardrobe", "Kitc...             nulos   
3  ["Extra pillows and blankets", "Washer", "Heat...             nulos   
4  ["Washer", "Air conditioning", "Dryer", "TV", ...             nulos   

   has_availability  calendar_last_scraped  first_review  last_review  \
0                 t             2024-06-24    2011-10-30   2024-04-30   
1                 t             2024-06-24    2011-10-30   2024-04-30   
2                 t             2024-06-24    2011-12-16   2024-06-16   
3                 t             2024-06-24    2012-04-21   2024-05-24   
4                 t             2024-06-24    2012-01-27   2015-08-14   

   license  instant_bookable  
0    nulos                 f  
1    nulos                 f  
2    nulos                 f  
3    nulos                 f  
4    nulos                 f  

[5 rows x 112 columns]

In [37]:
#Rellenamos valores nulos
dfh= dfh.fillna(method='bfill')
dfhf= dfh.fillna(method='ffill')

C:\Users\LEnri\AppData\Local\Temp\ipykernel_72696\1888419977.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfh= dfh.fillna(method='bfill')
C:\Users\LEnri\AppData\Local\Temp\ipykernel_72696\1888419977.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfhf= dfh.fillna(method='ffill')


In [38]:
dfh['price'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 6627 entries, 0 to 6626
Series name: price
Non-Null Count  Dtype  
--------------  -----  
6627 non-null   float64
dtypes: float64(1)
memory usage: 51.9 KB


**1 categorica**

In [39]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=dfh['price'].max()
Min=dfh['price'].min()
Limites= [Min, Max]
Limites

[np.float64(1.0), np.float64(9000.0)]

In [40]:
#Categorización de variables
#Declaramos 2 intervalos 
intervalos=np.linspace(105.0, 13283.0, 3)
intervalos

array([  105.,  6694., 13283.])

In [41]:
#Creamos las categorías 
categorias= ["cheap", "expensive"]

In [42]:
#Finalmente creamos las categorías en la columna numérica
dfh['price']=pd.cut(x= dfh['price'], bins=intervalos, labels= categorias )

In [43]:
#Rellenamos valores nulos
dfh= dfh.fillna(method='bfill')
dfhf= dfh.fillna(method='ffill')

C:\Users\LEnri\AppData\Local\Temp\ipykernel_72696\1888419977.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfh= dfh.fillna(method='bfill')
C:\Users\LEnri\AppData\Local\Temp\ipykernel_72696\1888419977.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfhf= dfh.fillna(method='ffill')


In [44]:
dfh['price'].isnull().sum()

np.int64(0)

In [45]:
vars_Indep = dfh[['bedrooms']]
#'bathrooms'
vars_Dep = dfh['price']
#'accommodates', 'host_response_rate', 'host_acceptance_rate', 'host_total_listings_count', 'reviews_per_month'

In [46]:
#Redefinimos las variables 
x= vars_Indep
y= vars_Dep

In [47]:
#dividimos el conjunto de datos en la parte de entrenamiento y pruba 
X_test, X_train, Y_test, Y_train= train_test_split(x,y, test_size=0.3, random_state=None)

In [48]:
escalar = StandardScaler()

In [49]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, Utilizaremos 
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [50]:
#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [51]:
#Entrenamos el modelo 
algoritmo.fit(X_train, Y_train)

LogisticRegression()

In [52]:
#realizamos una prediccion 
y_pred = algoritmo.predict(X_test)
y_pred

array(['cheap', 'cheap', 'cheap', ..., 'cheap', 'cheap', 'cheap'],
      dtype=object)

In [53]:
#Verifico la matriz de confusion 
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(Y_test, y_pred)
print('Matriz de Confusion')
print(matriz)

Matriz de Confusion
[[4631    0]
 [   7    0]]


In [54]:
#CAlculamos la prediccion del modelo 
from sklearn.metrics import precision_score

precision = precision_score(Y_test, y_pred, average="binary", pos_label="cheap")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.9984907287623976


In [55]:
#Calculamos la exactitud del modelo 
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(Y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.9984907287623976


In [56]:
#calculamos la sensibilidad del modelo 
from sklearn.metrics import recall_score

sensibilidad = recall_score(Y_test, y_pred, average="binary", pos_label="cheap")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
1.0


**2 Categoricas**

In [57]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=dfh['accommodates'].max()
Min=dfh['accommodates'].min()
Limites= [Min, Max]
Limites

[np.float64(1.0), np.float64(8.0)]

In [58]:
#Categorización de variables
#Declaramos 2 intervalos 
intervalos1=np.linspace(0.99, 10.1, 3)
intervalos1

array([ 0.99 ,  5.545, 10.1  ])

In [59]:
#Creamos las categorías 
categorias1= ["pocos", "manada"]

In [60]:
dfh['accommodates']

0       2.0
1       8.0
2       4.0
3       6.0
4       2.0
       ... 
6622    2.0
6623    5.0
6624    2.0
6625    2.0
6626    1.0
Name: accommodates, Length: 6627, dtype: float64

In [61]:
#Finalmente creamos las categorías en la columna numérica
dfh['accommodates']=pd.cut(x= dfh['accommodates'], bins=intervalos1, labels= categorias1 )

In [62]:
#Rellenamos valores nulos
dfh= dfh.fillna(method='bfill')
dfhf= dfh.fillna(method='ffill')

C:\Users\LEnri\AppData\Local\Temp\ipykernel_72696\1888419977.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfh= dfh.fillna(method='bfill')
C:\Users\LEnri\AppData\Local\Temp\ipykernel_72696\1888419977.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfhf= dfh.fillna(method='ffill')


In [63]:
dfh['accommodates'].isnull().sum()

np.int64(0)

In [65]:
vars_Indep_1 = dfh[['bedrooms']]
#'bathrooms'
vars_Dep_1 = dfh['accommodates']
#'accommodates', 'host_response_rate', 'host_acceptance_rate', 'host_total_listings_count', 'reviews_per_month'

In [66]:
#Redefinimos las variables 
x= vars_Indep_1
y= vars_Dep_1

In [67]:
#dividimos el conjunto de datos en la parte de entrenamiento y pruba 
X_test1, X_train1, Y_test1, Y_train1= train_test_split(x,y, test_size=0.3, random_state=None)

In [68]:
escalar1 = StandardScaler()

In [69]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, Utilizaremos 
X_train1 = escalar.fit_transform(X_train1)
X_test1 = escalar.transform(X_test1)

In [70]:
#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo1 = LogisticRegression()

In [71]:
#Entrenamos el modelo 
algoritmo1.fit(X_train1, Y_train1)

LogisticRegression()

In [72]:
#realizamos una prediccion 
y_pred1 = algoritmo1.predict(X_test1)
y_pred1

array(['pocos', 'pocos', 'pocos', ..., 'pocos', 'pocos', 'manada'],
      dtype=object)

In [73]:
#Verifico la matriz de confusion 
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(Y_test1, y_pred1)
print('Matriz de Confusion')
print(matriz)

Matriz de Confusion
[[ 111  197]
 [ 113 4217]]


In [74]:
#CAlculamos la prediccion del modelo 
from sklearn.metrics import precision_score

precision = precision_score(Y_test1, y_pred1, average="binary", pos_label="pocos")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.9553692795650204


In [75]:
#Calculamos la exactitud del modelo 
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(Y_test1, y_pred1)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.933160845191893


In [76]:
#calculamos la sensibilidad del modelo 
from sklearn.metrics import recall_score

sensibilidad = recall_score(Y_test1, y_pred1, average="binary", pos_label="pocos")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.9739030023094688


**3 Categoricas**

In [77]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=dfh['beds'].max()
Min=dfh['beds'].min()
Limites= [Min, Max]
Limites

[np.float64(0.0), np.float64(6.0)]

In [78]:
#Categorización de variables
#Declaramos 2 intervalos 
intervalos2=np.linspace(-0.1, 7.1, 3)
intervalos2


array([-0.1,  3.5,  7.1])

In [79]:
#Creamos las categorías 
categorias2= ["dormilones", "activos"]

In [80]:
dfh['beds']

0       1.0
1       6.0
2       3.0
3       3.0
4       1.0
       ... 
6622    1.0
6623    2.0
6624    1.0
6625    1.0
6626    1.0
Name: beds, Length: 6627, dtype: float64

In [81]:
#Finalmente creamos las categorías en la columna numérica
dfh['beds']=pd.cut(x= dfh['beds'], bins=intervalos2, labels= categorias2 )


In [82]:
#Rellenamos valores nulos
dfh= dfh.fillna(method='bfill')
dfhf= dfh.fillna(method='ffill')


C:\Users\LEnri\AppData\Local\Temp\ipykernel_72696\153006150.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfh= dfh.fillna(method='bfill')
C:\Users\LEnri\AppData\Local\Temp\ipykernel_72696\153006150.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfhf= dfh.fillna(method='ffill')


In [83]:
dfh['beds'].isnull().sum()

np.int64(0)

In [84]:
vars_Indep_2 = dfh[['bedrooms']]

vars_Dep_2 = dfh['beds']


In [85]:
#Redefinimos las variables 
x= vars_Indep_2
y= vars_Dep_2


In [86]:
#dividimos el conjunto de datos en la parte de entrenamiento y pruba 
X_test2, X_train2, Y_test2, Y_train2= train_test_split(x,y, test_size=0.3, random_state=None)


In [87]:
escalar2 = StandardScaler()

In [88]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, Utilizaremos 
X_train2 = escalar.fit_transform(X_train2)
X_test2 = escalar.transform(X_test2)


In [89]:
#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo2 = LogisticRegression()


In [90]:
#Entrenamos el modelo 
algoritmo2.fit(X_train2, Y_train2)


LogisticRegression()

In [91]:
#realizamos una prediccion 
y_pred2 = algoritmo2.predict(X_test2)
y_pred2


array(['dormilones', 'dormilones', 'dormilones', ..., 'dormilones',
       'dormilones', 'dormilones'], dtype=object)

In [92]:
#Verifico la matriz de confusion 
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(Y_test2, y_pred2)
print('Matriz de Confusion')
print(matriz)


Matriz de Confusion
[[   0  286]
 [   0 4352]]


In [93]:
#CAlculamos la prediccion del modelo 
from sklearn.metrics import precision_score
precision = precision_score(Y_test2, y_pred2, average="binary", pos_label="dormilones")
print('Precision del modelo:')
print(precision)


Precision del modelo:
0.9383354894351014


In [94]:
#Calculamos la exactitud del modelo 
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(Y_test2, y_pred2)
print('Exactitud del modelo:')
print(exactitud)


Exactitud del modelo:
0.9383354894351014


In [95]:
#calculamos la sensibilidad del modelo 
from sklearn.metrics import recall_score
sensibilidad = recall_score(Y_test2, y_pred2, average="binary", pos_label="dormilones")
print('Sensibilidad del modelo:')
print(sensibilidad)


Sensibilidad del modelo:
1.0


**4 categoricas**

In [96]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=dfh['bathrooms'].max()
Min=dfh['bathrooms'].min()
Limites= [Min, Max]
Limites


[np.float64(0.0), np.float64(2.5)]

In [97]:
#Categorización de variables
#Declaramos 2 intervalos 
intervalos3=np.linspace(-0.1, 4.6, 3)
intervalos3


array([-0.1 ,  2.25,  4.6 ])

In [98]:
#Creamos las categorías 
categorias3= ["extreñidos", "surrones"]


In [99]:
dfh['bathrooms']

0       1.0
1       2.5
2       1.0
3       2.0
4       2.0
       ... 
6622    1.0
6623    1.0
6624    1.0
6625    1.0
6626    1.0
Name: bathrooms, Length: 6627, dtype: float64

In [100]:
#Finalmente creamos las categorías en la columna numérica
dfh['bathrooms']=pd.cut(x= dfh['bathrooms'], bins=intervalos3, labels= categorias3 )


In [101]:
#Rellenamos valores nulos
dfh= dfh.fillna(method='bfill')
dfh= dfh.fillna(method='ffill')


C:\Users\LEnri\AppData\Local\Temp\ipykernel_72696\956806766.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfh= dfh.fillna(method='bfill')
C:\Users\LEnri\AppData\Local\Temp\ipykernel_72696\956806766.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfh= dfh.fillna(method='ffill')


In [102]:
dfh['bathrooms'].isnull().sum()

np.int64(0)

In [103]:
vars_Indep_3 = dfh[['bedrooms']]

vars_Dep_3 = dfh['bathrooms']


In [104]:
#Redefinimos las variables 
x= vars_Indep_3
y= vars_Dep_3


In [105]:

#dividimos el conjunto de datos en la parte de entrenamiento y pruba 
X_test3, X_train3, Y_test3, Y_train3= train_test_split(x,y, test_size=0.3, random_state=None)


In [106]:
escalar3 = StandardScaler()

In [107]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, Utilizaremos 
X_train3 = escalar.fit_transform(X_train3)
X_test3 = escalar.transform(X_test3)


In [108]:
#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo3 = LogisticRegression()


In [109]:
#Entrenamos el modelo 
algoritmo3.fit(X_train3, Y_train3)


LogisticRegression()

In [110]:
#realizamos una prediccion 
y_pred3 = algoritmo3.predict(X_test3)
y_pred3


array(['extreñidos', 'extreñidos', 'extreñidos', ..., 'extreñidos',
       'extreñidos', 'extreñidos'], dtype=object)

In [111]:
#Verifico la matriz de confusion 
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(Y_test3, y_pred3)
print('Matriz de Confusion')
print(matriz)


Matriz de Confusion
[[4624    0]
 [  14    0]]


In [112]:
#CAlculamos la prediccion del modelo 
from sklearn.metrics import precision_score
precision = precision_score(Y_test3, y_pred3, average="binary", pos_label="extreñidos")
print('Precision del modelo:')
print(precision)


Precision del modelo:
0.9969814575247952


In [113]:
#Calculamos la exactitud del modelo 
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(Y_test3, y_pred3)
print('Exactitud del modelo:')
print(exactitud)


Exactitud del modelo:
0.9969814575247952


In [114]:
#calculamos la sensibilidad del modelo 
from sklearn.metrics import recall_score
sensibilidad = recall_score(Y_test3, y_pred3, average="binary", pos_label="extreñidos")
print('Sensibilidad del modelo:')
print(sensibilidad)


Sensibilidad del modelo:
1.0


**5 Categoria**

In [115]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=dfh['host_total_listings_count'].max()
Min=dfh['host_total_listings_count'].min()
Limites= [Min, Max]
Limites


[np.float64(1.0), np.float64(544.0)]

In [116]:
dfh['host_total_listings_count']

0         1.0
1         1.0
2         1.0
3        19.0
4         2.0
        ...  
6622    260.0
6623      4.0
6624    150.0
6625     66.0
6626    150.0
Name: host_total_listings_count, Length: 6627, dtype: float64

In [117]:
#Categorización de variables
#Declaramos 2 intervalos 
intervalos4=np.linspace(0.99, 442.1, 3)
intervalos4


array([  0.99 , 221.545, 442.1  ])

In [118]:
#Creamos las categorías 
categorias4= ["pocas", "muchas"]


In [119]:
dfh['host_total_listings_count']

0         1.0
1         1.0
2         1.0
3        19.0
4         2.0
        ...  
6622    260.0
6623      4.0
6624    150.0
6625     66.0
6626    150.0
Name: host_total_listings_count, Length: 6627, dtype: float64

In [120]:
#Finalmente creamos las categorías en la columna numérica
dfh['host_total_listings_count']=pd.cut(x= dfh['host_total_listings_count'], bins=intervalos4, labels= categorias4 )


In [121]:
#Rellenamos valores nulos
dfh= dfh.fillna(method='bfill')
dfhf= dfh.fillna(method='ffill')


C:\Users\LEnri\AppData\Local\Temp\ipykernel_72696\153006150.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfh= dfh.fillna(method='bfill')
C:\Users\LEnri\AppData\Local\Temp\ipykernel_72696\153006150.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfhf= dfh.fillna(method='ffill')


In [122]:
dfh['host_total_listings_count'].isnull().sum()

np.int64(0)

In [123]:
vars_Indep_4 = dfh[['bedrooms']]

vars_Dep_4 = dfh['host_total_listings_count']


In [124]:
#Redefinimos las variables 
x= vars_Indep_4
y= vars_Dep_4


In [125]:
#dividimos el conjunto de datos en la parte de entrenamiento y pruba 
X_test4, X_train4, Y_test4, Y_train4= train_test_split(x,y, test_size=0.3, random_state=None)


In [126]:
escalar4 = StandardScaler()

In [127]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, Utilizaremos 
X_train4 = escalar.fit_transform(X_train4)
X_test4 = escalar.transform(X_test4)


In [128]:
#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo4 = LogisticRegression()


In [129]:
#Entrenamos el modelo 
algoritmo4.fit(X_train4, Y_train4)


LogisticRegression()

In [130]:
#realizamos una prediccion 
y_pred4 = algoritmo4.predict(X_test4)
y_pred4


array(['pocas', 'pocas', 'pocas', ..., 'pocas', 'pocas', 'pocas'],
      dtype=object)

In [131]:
#Verifico la matriz de confusion 
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(Y_test4, y_pred4)
print('Matriz de Confusion')
print(matriz)


Matriz de Confusion
[[   0  934]
 [   0 3704]]


In [132]:
#CAlculamos la prediccion del modelo 
from sklearn.metrics import precision_score
precision = precision_score(Y_test4, y_pred4, average="binary", pos_label="pocas")
print('Precision del modelo:')
print(precision)


Precision del modelo:
0.7986200948684777


In [133]:
#Calculamos la exactitud del modelo 
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(Y_test4, y_pred4)
print('Exactitud del modelo:')
print(exactitud)


Exactitud del modelo:
0.7986200948684777


In [134]:
#calculamos la sensibilidad del modelo 
from sklearn.metrics import recall_score
sensibilidad = recall_score(Y_test4, y_pred4, average="binary", pos_label="pocas")
print('Sensibilidad del modelo:')
print(sensibilidad)


Sensibilidad del modelo:
1.0


**FIN**